name: Deploy to EC2

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar para deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem

    - name: Fetch latest code on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@ec2-52-90-98-83.compute-1.amazonaws.com "cd /home/ubuntu/cyf-Cloud-Full_Stack_Project && git fetch && git pull"

    - name: Install dependencies and build
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@ec2-52-90-98-83.compute-1.amazonaws.com << 'EOF'
          source ~/.bashrc
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use --lts
          cd /home/ubuntu/cyf-Cloud-Full_Stack_Project
          npm install
          npm run build
          pm2 kill
          pm2 start npm --name "video-recommendations" -- start
          pm2 save
        EOF
    # - name: Restart the server
    #   run: |
    #     ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@ec2-52-90-98-83.compute-1.amazonaws.com "cd /home/ubuntu/cyf-Cloud-Full_Stack_Project && pm2 restart all"
