name: Deploy to EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/video-recommendations:latest

      - name: SSH and deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@ec2-52-90-98-83.compute-1.amazonaws.com << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/video-recommendations:latest
            docker stop video-recommendations || true
            docker rm video-recommendations || true
            docker run -d --restart unless-stopped -p 3000:3000 -p 3100:3100 --name video-recommendations ${{ secrets.DOCKER_USERNAME }}/video-recommendations:latest
          EOF
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}